### ISSUE TITLE
`nanobox run` (0.15.6) apparently downloads box image that does not boot

### ISSUE THREAD

**Issue by orospakr** [nanobox-io/nanobox-boot2docker#1]
![image](https://cloud.githubusercontent.com/assets/16714/10770169/394e1f62-7cc0-11e5-85e2-5b43aa41f92f.png)

At first glance, seems like it doesn't even have a boot sector.

If it matters, I did the standalone `nanobox` tool installation, using my system copy of Vagrant (1.7.4) and Virtualbox (5.0.8).

I haven't yet tried peeling apart the VMDK (booting a GNU Parted image or something against the VM and looking around), nor have I tried manually rebuilding it.

**Comment by tylerflint** [comment]
Thanks for the heads up!

I'm wondering if Vagrant downloaded the box, or if nanobox downloaded it. The box build process is currently in transition, so I'm wondering if you're caught in the middle. Can you try to run

```bash
nanobox box update
```

Thanks

@glinton I'm wondering if the recent atlas build has something to do with this?

**Comment by orospakr** [comment]
@tylerflint alas, that was one of the first things I tried!

**Comment by sdomino** [comment]
@glinton this is the error I'm getting:

"metadata.json" file for the box 'nanobox/boot2docker' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

http://docs.vagrantup.com/v2/boxes/format.html

**Comment by glinton** [comment]
I'm going to blame atlas on that one, I finally met the requirements for that metadata.json error on friday. Recently, while trying to get atlas to build a box, I've been plagued with errors on atlas' end like `* Post-processor failed: Error uploading: client: 504 GATEWAY_TIMEOUT`  and `* Post-processor failed: Error uploading: client: 408 REQUEST_TIMEOUT`.  But when a build actually completes and that is still there, I'll take full responsibility.

**Comment by tylerflint** [comment]
I don't want to open a can of worms here if it's not necessary, but I'm wondering if there is an alternative to atlas. Seems like we've struggled with atlas in the past. I definitely like to idea of atlas because we can setup automated builds. That said, I wonder if there's a way to do an automated build with something else, that would perhaps allow us to upload to s3 and use our existing process. 

I wonder if aws lambda would be an option...

**Comment by tylerflint** [comment]
@glinton For the interim, can we revoke the box from atlas and publish a build to s3 until we get this resolved?
